//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatPruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string nickName { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> idState { get; set; }
    
        public virtual State State { get; set; }
    }
}
